on:
  push:
    branches:
      - main

env: 
  RESOURCEGROUPNAME: "techradar-rg"
  LOCATION: "North Europe"
  IMAGENAME: "findy-wallet-pwa"
  REGISTRYNAME: "techradarcontainerregistry"
  DOCKERFILE: "Dockerfile"
  
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push webhook image to ACR
      uses: azure/docker-login@v1
      id: build-webhook
      with:
        login-server: ${{ env.REGISTRYNAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        build-args: FOLDER=virta
    - run: |
        docker build "$GITHUB_WORKSPACE" -f  ${{ env.DOCKERFILE }} -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
        docker tag ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }} ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:latest
        docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:latest