name: release
on:
  push:
    tags:
      - '*'
jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-wallet-pwa/local:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-wallet-pwa/local:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-wallet-pwa/local:latest
          cache-to: type=inline
          context: ./
          file: ./tools/env-docker/Dockerfile

  merge:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: merge
        run:  |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master