name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: install deps
        run: npm ci
      - name: build
        run: CI=true npm run build
      - name: lint
        run: npm run test:lint
      - name: test
        run: CI=true npm test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: setup env
        run: |
          cd tools/env
          make init-store
          docker-compose up -d
      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin
      - name: install deps
        run: npm ci
      - name: start app
        run: CI=true npm start &
      - name: test
        run: npm run test:e2e
      - name: Collect docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2.0.2
        with:
          dest: './tests_output/docker-logs'
      - name: archive logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: e2e-logs
          path: tests_output
