name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12'
      - name: install deps
        run: npm ci
      - name: build
        run: CI=true npm run build
      - name: lint
        run: npm run test:lint
      - name: test
        run: CI=true npm test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: test e2e flow
        uses: findy-network/e2e-test-action@master
        with:
          service: "pwa"
          service-context: ./
          service-dockerfile: ./tools/env-docker/Dockerfile
